### ISSUE TITLE
GLib-GObject-Warning errors are crashing the process

### ISSUE THREAD

**Issue by AshuGuptaGamer** [rsmbl/Resemble.js#218]
Hey, I am using Resemble.js to find similarities between 2 images. It used to work great before but once I changes the environment it randomly started crashing.

By environment I mean, I am using this lib for a Discord Bot. So the environment it is running is:
```yml
Main_Process:
  Child_Process1:
    Thread_Worker:
      Running The compare() function to compare tons of images.
  Child_Process2:
    Thread_Worker:
      Running The compare() function to compare tons of images.
```
Here is the error
![image](https://user-images.githubusercontent.com/59139918/179797608-d1df83cc-13ea-40ed-88ab-8e6fafe87291.png)
Here is another one
![image](https://user-images.githubusercontent.com/59139918/179797867-bd3686d4-7f62-4bca-bcf3-d3ae63604579.png)

Thanks
